/**
 * patternService.js - Servicio para la generación y borrado de patrones de turnos y guardias TES.
 */

import { saveTimeLog, getShiftTypes, getAllTimeLogs } from './shiftService.js';
import { setStorageItem, STORAGE_KEYS } from './storageService.js';
import { formatDateToISO } from '../utils/dateUtils.js';

/**
 * Genera el patrón de Guardias de 24h (1 día guardia + 3 días descanso)
 * 
 * @param {string} fechaInicioGuardia - Fecha inicio 'YYYY-MM-DD'
 * @param {number|null} numeroMeses - Número de meses (si no se especifica fechaFinCustom)
 * @param {string|null} fechaFinCustom - Fecha fin personalizada 'YYYY-MM-DD'
 */
export function generateGuardias24hPattern(fechaInicioGuardia, numeroMeses = 6, fechaFinCustom = null) {
  if (!fechaInicioGuardia) return;

  const startDate = new Date(fechaInicioGuardia + 'T00:00:00');
  let endDate;

  if (fechaFinCustom) {
    endDate = new Date(fechaFinCustom + 'T00:00:00');
  } else {
    endDate = new Date(startDate);
    endDate.setMonth(endDate.getMonth() + (numeroMeses || 6));
  }

  const shiftTypes = getShiftTypes();
  const guardiaShift = shiftTypes.find(s => s.id === 'guardia24') || { id: 'guardia24', horaInicio: '08:00', horaFin: '08:00', horasTeoricas: 24 };
  const libreShift = shiftTypes.find(s => s.id === 'libre') || { id: 'libre', horaInicio: '00:00', horaFin: '00:00', horasTeoricas: 0 };

  let currDate = new Date(startDate);
  let dayCounter = 0;

  while (currDate <= endDate) {
    const isoDate = formatDateToISO(currDate);

    if (dayCounter % 4 === 0) {
      saveTimeLog({
        fecha: isoDate,
        tipoTurnoId: 'guardia24',
        horaEntradaReal: guardiaShift.horaInicio,
        horaSalidaReal: guardiaShift.horaFin,
        horasTrabajadas: 24,
        horasExtra: 0,
        esFestivo: false,
        esPatronAuto: true,
        notas: 'Guardia 24h (Patrón Rotativo)'
      });
    } else {
      saveTimeLog({
        fecha: isoDate,
        tipoTurnoId: 'libre',
        horaEntradaReal: libreShift.horaInicio,
        horaSalidaReal: libreShift.horaFin,
        horasTrabajadas: 0,
        horasExtra: 0,
        esFestivo: false,
        esPatronAuto: true,
        notas: `Descanso Post-Guardia (${dayCounter % 4}/3) (Patrón Rotativo)`
      });
    }

    currDate.setDate(currDate.getDate() + 1);
    dayCounter++;
  }
}

/**
 * Genera el patrón de Sábados Alternos
 * 
 * @param {string} primerSabadoTrabajado 
 * @param {number|null} numeroMeses 
 * @param {string|null} fechaFinCustom 
 */
export function generateSabadosAlternosPattern(primerSabadoTrabajado, numeroMeses = 6, fechaFinCustom = null) {
  if (!primerSabadoTrabajado) return;

  let currDate = new Date(primerSabadoTrabajado + 'T00:00:00');
  let endDate;

  if (fechaFinCustom) {
    endDate = new Date(fechaFinCustom + 'T00:00:00');
  } else {
    endDate = new Date(currDate);
    endDate.setMonth(endDate.getMonth() + (numeroMeses || 6));
  }

  const shiftTypes = getShiftTypes();
  const sabadoShift = shiftTypes.find(s => s.id === 'sabado_alterno') || { id: 'sabado_alterno', horaInicio: '08:00', horaFin: '16:00', horasTeoricas: 8 };

  while (currDate <= endDate) {
    const isoDate = formatDateToISO(currDate);

    saveTimeLog({
      fecha: isoDate,
      tipoTurnoId: 'sabado_alterno',
      horaEntradaReal: sabadoShift.horaInicio,
      horaSalidaReal: sabadoShift.horaFin,
      horasTrabajadas: 8,
      horasExtra: 0,
      esFestivo: false,
      esPatronAuto: true,
      notas: 'Sábado Alterno Trabajado (Patrón Rotativo)'
    });

    currDate.setDate(currDate.getDate() + 14);
  }
}

/**
 * Comprueba si un registro se considera generado por un patrón automático
 */
export function isLogAutoGenerated(log) {
  if (!log) return false;
  if (log.esPatronAuto === true) return true;
  if (log.notas) {
    const n = log.notas.toLowerCase();
    if (n.includes('patrón rotativo') || n.includes('patron rotativo') || n.includes('post-guardia') || n.includes('sábado alterno')) {
      return true;
    }
  }
  return false;
}

/**
 * Cuenta los turnos que coinciden en el rango para la vista previa de borrado.
 */
export function previewDeletePatternInRange(startDateIso, endDateIso, onlyAutoGenerated = true) {
  const logs = getAllTimeLogs();

  const matchingLogs = logs.filter(log => {
    const inRange = log.fecha >= startDateIso && log.fecha <= endDateIso;
    if (!inRange) return false;

    if (onlyAutoGenerated) {
      return isLogAutoGenerated(log);
    }
    return true;
  });

  return {
    totalEncontrados: matchingLogs.length,
    autoGenerados: matchingLogs.filter(l => isLogAutoGenerated(l)).length,
    manuales: matchingLogs.filter(l => !isLogAutoGenerated(l)).length,
    matchingLogs
  };
}

/**
 * Borra los turnos dentro del rango especificado
 */
export function deletePatternInRange(startDateIso, endDateIso, onlyAutoGenerated = true) {
  const logs = getAllTimeLogs();

  const remainingLogs = logs.filter(log => {
    const inRange = log.fecha >= startDateIso && log.fecha <= endDateIso;
    if (!inRange) return true;

    if (onlyAutoGenerated) {
      const isAuto = isLogAutoGenerated(log);
      return !isAuto;
    } else {
      return false;
    }
  });

  setStorageItem(STORAGE_KEYS.TIME_LOGS, remainingLogs);
  return remainingLogs;
}
